language: php
php:
  - 5.3
  - 5.3.3
before_script:
  - composer self-update
  - composer install
  - phpenv rehash
script: phpunit -v --colors --coverage-text
notifications:
  email:
    - artodeto@bazzline.net
